Allow multiline comma-dangle, turn off no-restricted-syntax
AdaSupport/eslint-config-ada pull request #6
Opened 2020-11-04 01:03 UTC by ebumbulis

The `no-restricted-syntax` rule blocks `for (const var of arr)` style loops, which I'd like to use.

The `comma-dangle` change is something extra I tacked on here which I've wanted to do for a while. I think this makes diffs cleaner and avoids annoying errors when copy/pasting a line from a list. Based on the (admittedly minimal) response to the slack thread linked below from ages ago, it seems like people are generally in favour of this. Eventually I want this to be set to `always-multiline` (which enforces it) but I think `only-multiline` is a nice intermediate step that doesn't require us to reformat everything right now.

Slack thread on comma-dangle:
https://adasupport.slack.com/archives/CHATBHNTB/p1581525786000600

2020-11-04 15:44 UTC, lozog commented on index.js
> +    "no-restricted-syntax": "off",
what are the implications of turning this off? Is there any other restricted syntax that we don't want to accidentally start allowing?

2020-11-04 15:45 UTC, px0 commented on index.js
> +    "no-restricted-syntax": "off",
https://eslint.org/docs/rules/no-restricted-syntax

2020-11-04 15:46 UTC, px0 commented on index.js
> +    "no-restricted-syntax": "off",
these are all restrictable types: https://github.com/eslint/espree/blob/master/lib/ast-node-types.js
I'm not sure why anyone would want to disallow any of them, tbh. Or at least I'd start with allowing everything and adding to a blacklist if it's a problem for some reason

2020-11-04 15:49 UTC, lozog approved these changes

2020-11-04 15:51 UTC, ychenz commented on index.js
> +    "no-restricted-syntax": "off",
I think because Javascript has so many possible different syntax, allow everything may potentially also allows our code base to become messy very quickly.

2020-11-04 15:57 UTC, ychenz requested changes
In this case I think we should just make an exception for this statement `for (const element of my_array)`

2020-11-04 15:59 UTC, rinoc commented
I think the reasoning was that this syntax gets transpiled to generators, which includes a somewhat large package `regenerator-runtime` to get to work with older browsers.

2020-11-04 15:59 UTC, sevarubbo requested changes
Oh, we also need to update version in package.json

2020-11-04 15:59 UTC, sevarubbo commented on index.js
> +    "comma-dangle": ["error", "only-multiline"],
Can we do this in a separate PR? I also think that it would make sense to use `always-multiline` option to achieve consistent code style. We could set the rule to warning first. Or we could use --fix option to auto fix all rule violations.

2020-11-04 16:00 UTC, px0 commented
> In this case I think we should just make an exception for this statement `for (const element of my_array)`, instead of allowing everything.

@ychenz do you have reservations about any of the features in particular, or why would you prefer an allow-list over a deny-list?

2020-11-04 16:02 UTC, rinoc commented
> I think the reasoning was that this syntax gets transpiled to generators, which includes a somewhat large package `regenerator-runtime` to get to work with older browsers.

https://github.com/airbnb/javascript/issues/1271#issuecomment-283736133

2020-11-04 16:02 UTC, sevarubbo commented on index.js
> +    "no-restricted-syntax": "off",
Actually I would agree with Yuchen here

2020-11-04 16:03 UTC, sevarubbo commented
> > In this case I think we should just make an exception for this statement `for (const element of my_array)`, instead of allowing everything.
> 
> @ychenz do you have reservations about any of the features in particular, or why would you prefer an allow-list over a deny-list?

There's a number of examples here: https://eslint.org/docs/rules/no-restricted-syntax. E.g. this rule disallows `with` statement.

2020-11-04 16:06 UTC, px0 commented
> > > In this case I think we should just make an exception for this statement `for (const element of my_array)`, instead of allowing everything.
> > 
> > 
> > @ychenz do you have reservations about any of the features in particular, or why would you prefer an allow-list over a deny-list?
> 
> There's a number of examples here: https://eslint.org/docs/rules/no-restricted-syntax. E.g. this rule disallows `with` statement.

That's an example not a reason though ;)

2020-11-04 16:06 UTC, ebumbulis commented
Hmm, given the discussion I think it probably makes sense just to use the `some` workaround. I'll make a separate PR some other time for `comma-dangle`. Thanks for the feedback and insights everyone!

2020-11-04 16:08 UTC, sevarubbo requested changes
After a second though I don't think we should disable the rule completely. I would recommend disabling the rule case by cases where it's really needed, or better avoid restricted syntax.

2020-11-04 16:08 UTC, sevarubbo commented on index.js
> +    "no-restricted-syntax": "off",
This is the list of rules eslint-config-airbnb config disallows: https://github.com/airbnb/javascript/blob/a24dc34a4a2748c99006a48e997aa0a06b1d4d94/packages/eslint-config-airbnb-base/rules/style.js

I'm not sure we want to disable this rule completely.

2020-11-10 22:36 UTC, ebumbulis commented
Ended up using an alternative syntax option which doesn't require disabling this rule. Opening a separate PR for comma-dangle.

2020-11-10 22:36 UTC, closed without merging